### ISSUE TITLE
MODELS: Allow for tag configuration on Github PushEvent

### ISSUE THREAD

**Issue by Catalin-Andronie** [hassanhabib/ADotNet#56]
I would like to have the ability to trigger GitHub workflow runs on push events for specific tags.
Reference pipeline:

```yml
name: .Net
on:
  push:
    tags:
    - *
    - RELEASES
    - version/v1
    branches:
    - master
...
```
