### ISSUE TITLE
RELEASES: Add Git Tag on Merge to Main

### ISSUE THREAD

**Issue by cjdutoit** [hassanhabib/ADotNet#58]
# The Ask

Create a job that will add a Git tag `RELEASE` to only when the pull request is merged into the main branch.

## How will this be used

If a tag can be added on merge, then the tag can be used on other workflow runs i.e. if a build action run on main and it detects a tag `RELEASE` then we can automatically deploy a nuget package if build & test is a success.

**Comment by cjdutoit** [comment]
I think we can add a second job to do this.  Here is a code sample as a starting point...
```yaml
jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 0
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Setup .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.1.22110.4
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  add_tag:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged && startsWith(github.event.pull_request.title, 'RELEASES:') && contains(github.event.pull_request.labels.*.name, 'RELEASES')
    runs-on: windows-latest
    needs: [build, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add Git Tag
        run: |
          git tag -a "release-${{ github.run_number }}" -m "Release ${{ github.run_number }}"
          git push origin --tags
```
